//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComputacionContext : DbContext
    {
        public ComputacionContext()
            : base("name=ComputacionDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Facultad> Facultades { get; set; }
        public virtual DbSet<Carrera> Carreras { get; set; }
        public virtual DbSet<Estudiante> Estudiantes { get; set; }
        public virtual DbSet<OperadoraTelefono> OperadoraTelefonos { get; set; }
        public virtual DbSet<DetalleEstudianteTelefono> DetalleEstudianteTelefonos { get; set; }
    }
}
