//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDato.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Estudiante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estudiante()
        {
            this.DetalleEstudianteTelefonos = new HashSet<DetalleEstudianteTelefono>();
        }
    
        public int Id { get; set; }


        [Required(ErrorMessage ="El campo {0} es requerido")]
        public string Carnet { get; set; }


        [Required(ErrorMessage = "El campo {0} es requerido")]
        public string Nombre { get; set; }


        [Required(ErrorMessage = "El campo {0} es requerido")]
        public string Apellido { get; set; }


        [Required(ErrorMessage = "El campo {0} es requerido")]
        public string Edad { get; set; }


        [Required(ErrorMessage = "El campo {0} es requerido")]
        [Display(Name ="Carrera")]
        public int CarreraId { get; set; }
    
        public virtual Carrera Carrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleEstudianteTelefono> DetalleEstudianteTelefonos { get; set; }
    }
}
